---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name : install java openjdk8 on ubuntu 20.04
        apt: 
          name: openjdk-8-jre
          state: present
        when: ansible_os_family == "Debian"

      - name: install java openjdk8 on RedHat Machine 
        yum:
           name: java-1.8.0-amazon-corretto-devel
           state: present  
        when: ansible_os_family == "RedHat"

