---
- hosts: all
  become: yes
  tasks:
      - name : install java openjdk8 on ubuntu 20.04
        apt: 
          name: openjdk-8-jre
          state: present
        when: ansible_os_family == "Debian"

      # - name: install pyhton 
      #   yum:
      #      name: python2.7
      #      state: present  
      #   when: ansible_os_family == "RedHat"

      # - name: Set Python interpreter for Ansible
      #   set_fact:
      #     ansible_python_interpreter: /usr/bin/python2.7


      - name: install java openjdk8 on RedHat Machine 
        yum:
           name: java-1.8.0-openjdk-devel
           state: present  
        when: ansible_os_family == "RedHat"

